export const sidebarConfig = {
  superadmin: ['CustomerManagement', 'UserManagement', 'ChangePassword', 'AddDevice', 'DeviceLocation', 'AppVersion'],
  systemspecialist: ['Dashboard', 'ScadaView', 'Location', 'UserManagement', 'Report', 'EnergySaved', 'ChangePassword',
    'Device', 'AddDevice', 'DeviceLocation', 'DeviceConfiguration', 'MeterGeneralAlert', 'EmailConfig',
    'MasterManageCom', 'ManageDeviceresult', 'ManageMovableResult', 'ManageSensorDeviceresult', 'ProtocolJSONResult',
    'CronJobData', 'EmailConfigList', 'ReportUserList', 'AlertHistoryLog' // 'Vendor',
  ],
  admin: ['Dashboard', 'Location', 'UserManagement',
    // 'Vendor',
    'ReportUserList', 'Report', 'EnergySaved', 'ChangePassword', 'AddDevice', 'DeviceLocation', 'DeviceConfiguration', 'EmailConfig'],
  manager: ['Dashboard', 'Location', 'UserManagement',
    // 'Vendor',
    'ReportUserList', 'ChangePassword', 'AddDevice', 'DeviceLocation', 'DeviceConfiguration', 'Report', 'EnergySaved'],
  user: ['ReportUserList', 'Dashboard', 'ChangePassword', /*'Location', 'AddDevice', 'DeviceLocation', 'DeviceConfiguration'*/],
};
// 'GasCylinder'
export const crudConfig = {
  dashboard: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: true,
    },
  },
  location: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: false,
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  emailconfig: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: false,
    },
    manager: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  usermanagement: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  vendor: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: true,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  gascylinder: {
    superadmin: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    manager: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    user: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
  },
  changepassword: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: true,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  device: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  report: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: true,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },
  EnergySaved: {
    superadmin: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: true,
    },
    manager: {
      view: true,
      add: true,
      edit: true,
      delete: false,
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
    },
  },

  devicelocation: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
      changeDeviceMode: {
        view: true,
        add: true,
        edit: true,
        delete: true,
      },
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: true,
        add: false,
        edit: true,
        delete: false,
      },
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: true,
        delete: false,
      },
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
    },
  },
  DeviceConfiguration: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
      changeDeviceMode: {
        view: true,
        add: true,
        edit: true,
        delete: true,
      },
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: true,
        add: false,
        edit: true,
        delete: false,
      },
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: true,
        delete: false,
      },
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
    },
  },
  MeterGeneralAlert: {
    systemspecialist: {
      view: true,
      add: true,
      edit: true,
      delete: true,
      changeDeviceMode: {
        view: true,
        add: true,
        edit: true,
        delete: true,
      },
    },
    admin: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: true,
        add: false,
        edit: true,
        delete: false,
      },
    },
    manager: {
      view: true,
      add: false,
      edit: true,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: true,
        delete: false,
      },
    },
    user: {
      view: true,
      add: false,
      edit: false,
      delete: false,
      changeDeviceMode: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
    },
  },
};
